#!/bin/bash
echo "Installing dependencies..."
sudo apt-get update
sudo apt-get -y install build-essential libboost-all-dev libminiupnpc-dev git libssl-dev libdb++-dev
echo "Downloading and Compiling Motocoin..."
git clone https://github.com/motocoin-dev/motocoin
sudo make -C /home/$SUDO_USER/motocoin/src/ -f makefile.unix
echo "Done!" 
echo "Now just run ./motocoind on /home/$SUDO_USER/motocoin/src"
